name: rebrand_cli
description: Production-grade rebranding CLI for Flutter.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1